name: Deploy to Server via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar Conteúdo do index.php no Ambiente do GitHub Actions # Pode remover este passo depois de tudo funcionar
        run: |
          echo "Conteúdo de index.php encontrado na raiz do repositório no runner:"
          cat index.php
          echo "--- Fim da verificação do index.php ---"

      - name: Preparar pacote para deploy (excluir itens indesejados)
        run: |
          set -e
          mkdir -p deploy
          rsync -a --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".gitignore" \
            --exclude ".gitattributes" \
            --exclude "node_modules" \
            --exclude "tests" \
            --exclude "docs" \
            --exclude ".env" \
            ./ deploy/

      - name: Deploy via SCP (enviar somente conteúdo de deploy/)
        uses: appleboy/scp-action@v0.1.4 # Mantenha esta versão, ela funcionará com a correção do 'source'
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 65002
          source: "deploy/"
          target: "public_html/updates/"
          overwrite: true

      - name: Mensagem final
        run: echo "Deployment para o servidor concluído!"
