name: Deploy to Server via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # (Opcional) Você pode manter este passo para depuração, se quiser ver o conteúdo do index.php
      - name: Verify index.php content (for debugging - can remove later)
        run: |
          echo "Content of index.php found in the repository root on the runner:"
          cat index.php
          echo "--- End of index.php verification ---"

      - name: Prepare package for deploy (exclude unwanted items)
        run: |
          set -e
          mkdir -p deploy
          rsync -a --delete \
            --exclude ".git/" \ 
            --exclude ".github/" \ 
            --exclude ".gitignore" \
            --exclude ".gitattributes" \
            --exclude "node_modules/" \
            --exclude "tests/" \
            --exclude "docs/" \
            --exclude ".env" \
            ./ deploy/ 

      - name: Deploy via SCP (send only content from deploy/)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 65002
          source: "deploy/" 
          target: "public_html/updates/"
          overwrite: true 

      - name: Final Message
        run: echo "Deployment to server completed!"
