name: Deploy to Server via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar pacote para deploy 
        run: |
          set -e
          mkdir -p deploy
          rsync -a --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".gitignore" \
            --exclude ".gitattributes" \
            --exclude "node_modules" \
            --exclude "tests" \
            --exclude "docs" \
            --exclude ".env" \
            ./ deploy/

      - name: Deploy via SCP (enviar somente conteúdo de deploy/)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          source: "deploy/*"
          target: "public_html/updates"

      - name: Mensagem final
        run: echo "Deployment para o servidor concluído!"
